#!/usr/bin/env bash

set -e

PYTHONPATH=src python \
    src/facto/algorithm/sim/main1_sample_masked_success_rates.py \
    --mask_proportions 0 0.01 0.1 0.5 0.9 \
    --max_shots 200_000 \
    --max_semiprime 10000 \
    --save_resume_path assets/masked_success_stats.csv

PYTHONPATH=src python \
    src/facto/algorithm/estimates/main1_generate_cost_table_data.py \
    --csv_path out/cost_variations.csv \
    --min_n 1024 \
    --max_n 8192 \
    --power_of_2_multipliers 1 1.5